name: Backend CI

on:
  push:
    branches: [ backend ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ backend ]
    paths:
      - 'backend/**'

jobs:
  backend-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: Install Dependencies
      working-directory: ./backend
      run: npm ci
    
    - name: Run Linting
      working-directory: ./backend
      run: npm run lint
    
    - name: Run Tests
      working-directory: ./backend
      run: npm test
    
    - name: Build
      working-directory: ./backend
      run: npm run build
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-build
        path: backend/dist 