name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, frontend, backend ]
  pull_request:
    branches: [ main, master, frontend, backend ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install Root Dependencies
      run: |
        if [ -f "package.json" ]; then
          npm ci
        else
          echo "No root package.json found, skipping root dependencies"
        fi
    
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: |
        if [ -f "package.json" ]; then
          npm ci
        else
          echo "No frontend package.json found"
          exit 1
        fi
    
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: |
        if [ -f "package.json" ]; then
          npm ci
        else
          echo "No backend package.json found"
          exit 1
        fi
    
    - name: Run Frontend Linting
      working-directory: ./frontend
      run: |
        if [ -f "package.json" ]; then
          npm run lint
        else
          echo "No frontend package.json found"
          exit 1
        fi
    
    - name: Run Backend Linting
      working-directory: ./backend
      run: |
        if [ -f "package.json" ]; then
          npm run lint
        else
          echo "No backend package.json found"
          exit 1
        fi
    
    - name: Run Frontend Tests
      working-directory: ./frontend
      run: |
        if [ -f "package.json" ]; then
          npm test
        else
          echo "No frontend package.json found"
          exit 1
        fi
    
    - name: Run Backend Tests
      working-directory: ./backend
      run: |
        if [ -f "package.json" ]; then
          npm test
        else
          echo "No backend package.json found"
          exit 1
        fi
    
    - name: Build Frontend
      working-directory: ./frontend
      run: |
        if [ -f "package.json" ]; then
          npm run build
        else
          echo "No frontend package.json found"
          exit 1
        fi
    
    - name: Build Backend
      working-directory: ./backend
      run: |
        if [ -f "package.json" ]; then
          npm run build
        else
          echo "No backend package.json found"
          exit 1
        fi

  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Production
      run: |
        echo "Deploying to production..."
        # Add your deployment commands here 