name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, frontend, backend ]
  pull_request:
    branches: [ main, master, frontend, backend ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install Dependencies
      run: |
        npm ci
        cd frontend && npm ci
        cd ../backend && npm ci
    
    - name: Run Linting
      run: |
        npm run lint
        cd frontend && npm run lint
        cd ../backend && npm run lint
    
    - name: Run Tests
      run: |
        npm test
        cd frontend && npm test
        cd ../backend && npm test
    
    - name: Build
      run: |
        cd frontend && npm run build
        cd ../backend && npm run build

  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Production
      run: |
        echo "Deploying to production..."
        # Add your deployment commands here 